<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.53" os="" host="EXTRA-PC-71"><DocLocation><![CDATA[C:\Git\TestGit\jenkins_uft_git]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[jenkins_uft_git]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:52]]></Time>
<TimeTick>1570687912</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:52]]></Time>
<TimeTick>1570687912</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:53]]></Time>
<TimeTick>1570687913</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:53]]></Time>
<TimeTick>1570687913</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:53]]></Time>
<TimeTick>1570687913</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:54]]></Time>
<TimeTick>1570687914</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:54]]></Time>
<TimeTick>1570687914</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login Failed.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:56]]></Time>
<TimeTick>1570687916</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Failed.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Hello.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:56]]></Time>
<TimeTick>1570687916</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Hello.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Login Authorization]]></Obj>
<Details ><![CDATA[Login Sucessfull.]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:56]]></Time>
<TimeTick>1570687916</TimeTick>
<NodeArgs eType="User" icon="11" nRep="26" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Authorization]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:57]]></Time>
<TimeTick>1570687917</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:57]]></Time>
<TimeTick>1570687917</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-10-2019 - 11:41:52" eTime="10-10-2019 - 11:41:57" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[jenkins_uft_git Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T17" iterID="2" >
<Action rID="T18">
<AName><![CDATA[Action1]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:57]]></Time>
<TimeTick>1570687917</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:57]]></Time>
<TimeTick>1570687917</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="37" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="36" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:58]]></Time>
<TimeTick>1570687918</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["joh"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:58]]></Time>
<TimeTick>1570687918</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:58]]></Time>
<TimeTick>1570687918</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OK.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:58]]></Time>
<TimeTick>1570687918</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:58]]></Time>
<TimeTick>1570687918</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Login Failed.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:59]]></Time>
<TimeTick>1570687919</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Failed.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Login Failed]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:59]]></Time>
<TimeTick>1570687919</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:59]]></Time>
<TimeTick>1570687919</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="51" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Failed]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Login Authorization]]></Obj>
<Details ><![CDATA[Something wrong for agent name/pwd.]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:59]]></Time>
<TimeTick>1570687919</TimeTick>
<NodeArgs eType="User" icon="11" nRep="53" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Authorization]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:59]]></Time>
<TimeTick>1570687919</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:41:59]]></Time>
<TimeTick>1570687919</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-10-2019 - 11:41:57" eTime="10-10-2019 - 11:41:59" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="33" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="32" status="Passed" >
<Disp><![CDATA[jenkins_uft_git Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T32" iterID="3" >
<Action rID="T33">
<AName><![CDATA[Action1]]></AName>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:00]]></Time>
<TimeTick>1570687920</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:00]]></Time>
<TimeTick>1570687920</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="64" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="63" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:00]]></Time>
<TimeTick>1570687920</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["joh"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:00]]></Time>
<TimeTick>1570687920</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:01]]></Time>
<TimeTick>1570687921</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="71" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[OK.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:01]]></Time>
<TimeTick>1570687921</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:01]]></Time>
<TimeTick>1570687921</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="68" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Login Authorization]]></Obj>
<Details ><![CDATA[Agentname/Password is missing]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:01]]></Time>
<TimeTick>1570687921</TimeTick>
<NodeArgs eType="User" icon="11" nRep="76" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Authorization]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-10-2019 - 11:42:00" eTime="10-10-2019 - 11:42:01" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="60" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="59" status="Passed" >
<Disp><![CDATA[jenkins_uft_git Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T42" iterID="4" >
<Action rID="T43">
<AName><![CDATA[Action1]]></AName>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:02]]></Time>
<TimeTick>1570687922</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:02]]></Time>
<TimeTick>1570687922</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="84" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="83" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:02]]></Time>
<TimeTick>1570687922</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:02]]></Time>
<TimeTick>1570687922</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="89" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:03]]></Time>
<TimeTick>1570687923</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="91" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[OK.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:03]]></Time>
<TimeTick>1570687923</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="93" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:03]]></Time>
<TimeTick>1570687923</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="95" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="88" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Login Authorization]]></Obj>
<Details ><![CDATA[Agentname/Password is missing]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:03]]></Time>
<TimeTick>1570687923</TimeTick>
<NodeArgs eType="User" icon="11" nRep="96" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Authorization]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-10-2019 - 11:42:01" eTime="10-10-2019 - 11:42:03" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="80" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="79" status="Passed" >
<Disp><![CDATA[jenkins_uft_git Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T52" iterID="5" >
<Action rID="T53">
<AName><![CDATA[Action1]]></AName>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:03]]></Time>
<TimeTick>1570687923</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:03]]></Time>
<TimeTick>1570687923</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="104" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="103" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:04]]></Time>
<TimeTick>1570687924</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:04]]></Time>
<TimeTick>1570687924</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="109" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["hp"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:05]]></Time>
<TimeTick>1570687925</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="111" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[OK.GetROProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:05]]></Time>
<TimeTick>1570687925</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="113" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.GetROProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:05]]></Time>
<TimeTick>1570687925</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Login Failed.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:07]]></Time>
<TimeTick>1570687927</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="117" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Failed.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Hello.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:07]]></Time>
<TimeTick>1570687927</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Hello.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="108" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[Login Authorization]]></Obj>
<Details ><![CDATA[Login Sucessfull.]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:07]]></Time>
<TimeTick>1570687927</TimeTick>
<NodeArgs eType="User" icon="11" nRep="119" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Authorization]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:08]]></Time>
<TimeTick>1570687928</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-10-2019 - 11:42:08]]></Time>
<TimeTick>1570687928</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="122" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="121" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-10-2019 - 11:42:03" eTime="10-10-2019 - 11:42:08" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="100" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="99" status="Passed" >
<Disp><![CDATA[jenkins_uft_git Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10-10-2019 - 11:41:49" eTime="10-10-2019 - 11:42:08" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test jenkins_uft_git Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>