<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.53" os="" host="EXTRA-PC-80"><DocLocation><![CDATA[C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\Drivers\Driver1]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Driver1]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:01]]></Time>
<TimeTick>1570188361</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:01]]></Time>
<TimeTick>1570188361</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" MovieMarker="MARK2" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" MovieMarker="MARK1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:13]]></Time>
<TimeTick>1570188373</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["John"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:13]]></Time>
<TimeTick>1570188373</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" MovieMarker="MARK3" >
<Disp><![CDATA[agentName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[2043507264]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["HP"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:14]]></Time>
<TimeTick>1570188374</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" MovieMarker="MARK4" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[2045357632]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:15]]></Time>
<TimeTick>1570188375</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" MovieMarker="MARK5" >
<Disp><![CDATA[OK.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[2039985696]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Hello.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:16]]></Time>
<TimeTick>1570188376</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" MovieMarker="MARK6" >
<Disp><![CDATA[Hello.Exist]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[2035401472]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:17]]></Time>
<TimeTick>1570188377</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" MovieMarker="MARK7" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Exist]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[1117634]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:17]]></Time>
<TimeTick>1570188377</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" MovieMarker="MARK8" >
<Disp><![CDATA[Micro Focus MyFlight Sample.close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:18]]></Time>
<TimeTick>1570188378</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:18]]></Time>
<TimeTick>1570188378</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Passed" MovieMarker="MARK10" >
<Disp><![CDATA[Run "C:\Program Files (x86)\Micro Focus\Unified Functional Testing\samples\Flights Application\FlightsGUI.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="27" status="Passed" MovieMarker="MARK9" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["John"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:29]]></Time>
<TimeTick>1570188389</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" MovieMarker="MARK11" >
<Disp><![CDATA[agentName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[2043507264]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["HP"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:29]]></Time>
<TimeTick>1570188389</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" MovieMarker="MARK12" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[2045357632]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:30]]></Time>
<TimeTick>1570188390</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = OK<br>devname = okButton<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:30]]></Time>
<TimeTick>1570188390</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" status="Warning" nType="Description" MovieMarker="MARK14" >
<Disp><![CDATA[OK]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[2039985696]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="35" status="Failed" nType="Run Error" MovieMarker="MARK13" >
<Disp><![CDATA[OK]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[2039985696]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" status="Failed" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[2492952]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:31]]></Time>
<TimeTick>1570188391</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled<BR/>Function file: C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs<BR/>Line (17): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfButton(&quot;OK&quot;).Click&quot;.]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:31]]></Time>
<TimeTick>1570188391</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="38" status="Failed" MovieMarker="MARK15" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="16" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[1511030]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Hello.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[04-10-2019 - 16:56:33]]></Time>
<TimeTick>1570188393</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" MovieMarker="MARK16" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Hello.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[fromCity]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"fromCity"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:00]]></Time>
<TimeTick>1570188420</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:00]]></Time>
<TimeTick>1570188420</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" status="Warning" nType="Parent description" MovieMarker="MARK18" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="51" status="Failed" nType="Run Error" MovieMarker="MARK17" >
<Disp><![CDATA[fromCity]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" status="Failed" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[1511030]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:00]]></Time>
<TimeTick>1570188420</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;fromCity&quot; object's parent &quot;Micro Focus MyFlight Sample&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs<BR/>Line (38): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfComboBox(&quot;fromCity&quot;).Select &quot;Denver&quot;&quot;.]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:00]]></Time>
<TimeTick>1570188420</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="54" status="Failed" MovieMarker="MARK19" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="37" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[toCity]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"toCity"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:21]]></Time>
<TimeTick>1570188441</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:21]]></Time>
<TimeTick>1570188441</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="66" status="Warning" nType="Parent description" MovieMarker="MARK21" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="65" status="Failed" nType="Run Error" MovieMarker="MARK20" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[toCity]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="53" status="Failed" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:21]]></Time>
<TimeTick>1570188441</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;toCity&quot; object's parent &quot;Micro Focus MyFlight Sample&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs<BR/>Line (39): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfComboBox(&quot;toCity&quot;).Select &quot;Los Angeles&quot;&quot;.]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:21]]></Time>
<TimeTick>1570188441</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" status="Failed" MovieMarker="MARK22" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="38" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[WpfImage_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"WpfImage_3"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:42]]></Time>
<TimeTick>1570188462</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:42]]></Time>
<TimeTick>1570188462</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="80" status="Warning" nType="Parent description" MovieMarker="MARK24" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="79" status="Failed" nType="Run Error" MovieMarker="MARK23" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[WpfImage_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" status="Failed" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:42]]></Time>
<TimeTick>1570188462</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;WpfImage_3&quot; object's parent &quot;Micro Focus MyFlight Sample&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs<BR/>Line (40): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfImage(&quot;WpfImage_3&quot;).Click 6,15&quot;.]]></Details>
<Time><![CDATA[04-10-2019 - 16:57:42]]></Time>
<TimeTick>1570188462</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" status="Failed" MovieMarker="MARK25" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="39" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Mo]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Mo"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:03]]></Time>
<TimeTick>1570188483</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:03]]></Time>
<TimeTick>1570188483</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" status="Warning" nType="Parent description" MovieMarker="MARK27" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="93" status="Failed" nType="Run Error" MovieMarker="MARK26" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Mo]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="81" status="Failed" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:03]]></Time>
<TimeTick>1570188483</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Mo&quot; object's parent &quot;Micro Focus MyFlight Sample&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs<BR/>Line (41): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfCalendar(&quot;Mo&quot;).SetDate &quot;17-Oct-2019&quot;&quot;.]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:03]]></Time>
<TimeTick>1570188483</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="96" status="Failed" MovieMarker="MARK28" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="40" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Class]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Class"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:24]]></Time>
<TimeTick>1570188504</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:24]]></Time>
<TimeTick>1570188504</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="108" status="Warning" nType="Parent description" MovieMarker="MARK30" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="107" status="Failed" nType="Run Error" MovieMarker="MARK29" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Class]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="95" status="Failed" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:24]]></Time>
<TimeTick>1570188504</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Class&quot; object's parent &quot;Micro Focus MyFlight Sample&quot; (class WpfWindow).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs<BR/>Line (42): &quot;WpfWindow(&quot;Micro Focus MyFlight Sample&quot;).WpfComboBox(&quot;Class&quot;).Select &quot;Business&quot;&quot;.]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:24]]></Time>
<TimeTick>1570188504</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="110" status="Failed" MovieMarker="MARK31" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="41" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[numOfTickets]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"numOfTickets"&nbsp;object's&nbsp;parent&nbsp;"Micro&nbsp;Focus&nbsp;MyFlight&nbsp;Sample"&nbsp;(class&nbsp;WpfWindow).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:45]]></Time>
<TimeTick>1570188525</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>wpftypename = window<br>regexpwndtitle = Micro Focus MyFlight Sample Application<br>devname = Micro Focus MyFlight Sample Application<br>]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:45]]></Time>
<TimeTick>1570188525</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="122" status="Warning" nType="Parent description" MovieMarker="MARK33" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="121" status="Failed" nType="Run Error" MovieMarker="MARK32" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[numOfTickets]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="109" status="Failed" Source="C:\Users\Nikita.Chaudhari\Desktop\Hybide_Framework\FunctionLibrary\User.vbs" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[04-10-2019 - 16:58:45]]></Time>
<TimeTick>1570188525</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>