<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.53" os="" host="EXTRA-PC-80"><DocLocation><![CDATA[C:\Git\UFTTrial\TestGit\DemoTest]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[DemoTest]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:19]]></Time>
<TimeTick>1570618999</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["John"]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:19]]></Time>
<TimeTick>1570618999</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" MovieMarker="MARK1" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[agentName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[2096551840]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5d9dbe17e6c7c81892d6"]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:20]]></Time>
<TimeTick>1570619000</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" MovieMarker="MARK2" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[2096552368]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:20]]></Time>
<TimeTick>1570619000</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" MovieMarker="MARK3" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[2099406728]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:21]]></Time>
<TimeTick>1570619001</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" MovieMarker="MARK4" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[fromCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[2096552608]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Portland"]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:22]]></Time>
<TimeTick>1570619002</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" MovieMarker="MARK5" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[toCity.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[2099407304]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Business"]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:23]]></Time>
<TimeTick>1570619003</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" MovieMarker="MARK6" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Class.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[2099406296]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:24]]></Time>
<TimeTick>1570619004</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" MovieMarker="MARK7" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 0]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:24]]></Time>
<TimeTick>1570619004</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" MovieMarker="MARK8" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[2099406632]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:25]]></Time>
<TimeTick>1570619005</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" MovieMarker="MARK9" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[0]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["niki"]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:25]]></Time>
<TimeTick>1570619005</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" MovieMarker="MARK10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[passengerName.Set]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[2096553472]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:26]]></Time>
<TimeTick>1570619006</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" MovieMarker="MARK11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ORDER.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[2099406680]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-10-2019 - 16:33:27]]></Time>
<TimeTick>1570619007</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="32" MovieMarker="MARK12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[787652]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="09-10-2019 - 16:32:53" eTime="09-10-2019 - 16:33:27" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" MovieMarker="MARK0" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[DemoTest Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="09-10-2019 - 16:32:49" eTime="09-10-2019 - 16:33:27" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test DemoTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>